"""Self-contained Reference Ladder research UI."""

REFERENCE_LADDER_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Reference Ladder · BTC research</title>
<style>
:root{--bg:#05070a;--panel:#0b1017;--line:#233044;--txt:#edf3fb;--muted:#8090a5;--green:#19c37d;--red:#ff4d5f;--amber:#f2b84b;--blue:#3aa0ff;--violet:#a78bfa;font-family:Inter,Segoe UI,sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--txt)}header{display:flex;gap:12px;align-items:center;padding:13px 18px;border-bottom:1px solid var(--line);background:#090d13;position:sticky;top:0;z-index:2}.brand{font-weight:800;letter-spacing:.08em;text-transform:uppercase}.nav,.btn{color:var(--txt);background:#101722;border:1px solid var(--line);border-radius:6px;padding:7px 11px;text-decoration:none;cursor:pointer}.btn.go{border-color:#1f8b61;color:#55e6a3}.btn.study{border-color:#896927;color:#ffd77b}.spacer{flex:1}.status{color:var(--muted);font:12px Consolas,monospace}
main{padding:16px;max-width:1500px;margin:auto}.card{background:var(--panel);border:1px solid var(--line);border-radius:9px;margin-bottom:14px;overflow:hidden}.head{padding:11px 14px;border-bottom:1px solid var(--line);font-weight:700}.body{padding:13px 14px}.warn{color:var(--amber);font-size:12px}.err{color:var(--red)}.muted{color:var(--muted)}
.form{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:10px}.form label{font-size:11px;color:var(--muted);display:flex;flex-direction:column;gap:4px}.form input,.form select{background:#0e151f;color:var(--txt);border:1px solid var(--line);border-radius:5px;padding:7px}.actions{display:flex;gap:9px;margin-top:12px;align-items:center;flex-wrap:wrap}
.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.stat{background:#080c12;border:1px solid #182235;border-radius:6px;padding:9px}.k{font-size:10px;color:var(--muted);text-transform:uppercase}.v{font:700 16px Consolas,monospace;margin-top:3px}.pos{color:var(--green)}.neg{color:var(--red)}
.chart{width:100%;height:280px;background:#070b10;border:1px solid #182235;border-radius:6px}.legend{display:flex;gap:18px;font:11px Consolas,monospace;margin:7px 0}.sw{display:inline-block;width:16px;height:3px;vertical-align:middle;margin-right:5px}.tablewrap{overflow:auto;max-height:520px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:7px 8px;border-bottom:1px solid #172132;text-align:right;white-space:nowrap}th{position:sticky;top:0;background:#0d141e;color:var(--muted)}th:first-child,td:first-child{text-align:left}pre{white-space:pre-wrap;color:#9fb0c5;font-size:11px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:1050px){.form{grid-template-columns:repeat(3,1fr)}.stats{grid-template-columns:repeat(3,1fr)}.grid2{grid-template-columns:1fr}}@media(max-width:600px){.form{grid-template-columns:1fr 1fr}.stats{grid-template-columns:1fr 1fr}}
</style></head><body>
<header><span class="brand">Reference Ladder</span><a class="nav" href="/strategies">Strategy Library</a><a class="nav" href="/paper">Paper Trading</a><span class="spacer"></span><span class="status" id="status">ready</span></header>
<main>
<section class="card"><div class="head">BTCUSDT 1-minute configuration</div><div class="body">
<p class="warn">Research/backtesting only. The reference signal is not a trade. Ladder entries carry explicit spread, commission, size-dependent slippage, financing, margin and liquidation.</p>
<div class="form">
<label>Start date<input id="start" value="2018-01-01"></label><label>End date<input id="end" placeholder="latest"></label>
<label>Starting capital<input id="capital" type="number" value="100000"></label><label>Leverage<input id="leverage" type="number" value="100"></label>
<label>Trigger distance ($)<input id="trigger" type="number" value="800"></label><label>Level step ($)<input id="step" type="number" value="500"></label>
<label>Max levels<input id="levels" type="number" value="4"></label><label>Distance mode<select id="distance"><option value="fixed">Fixed USD</option><option value="atr">ATR-scaled</option></select></label>
<label>Sizing mode<select id="sizing"><option value="auto">Auto balance-scaled</option><option value="fixed">Fixed BTC</option></select></label>
<label>Fixed BTC sizes<input id="fixed" value="10,20,40,80"></label><label>Auto multipliers<input id="multipliers" value="1,2,4,8"></label><label>BTC / $1K<input id="auto" type="number" step="0.01" value="0.05"></label>
<label>Round-turn spread ($)<input id="spread" type="number" value="10"></label><label>Commission rate<input id="commission" type="number" step="0.0001" value="0.0004"></label><label>Funding / 8h<input id="funding" type="number" step="0.0001" value="0.0001"></label>
<label>Base slippage ($)<input id="baseSlip" type="number" step="0.1" value="1"></label><label>Size slippage ($/BTC^0.5)<input id="sizeSlip" type="number" step="0.05" value="0.35"></label><label>Maintenance margin rate<input id="maintenance" type="number" step="0.001" value="0.005"></label>
<label>Profit target points<input id="profit" type="number" placeholder="off"></label><label>Max cycle loss (%)<input id="loss" type="number" placeholder="off"></label><label>Max duration hours<input id="duration" type="number" placeholder="off"></label>
<label>Trading start hour UTC<input id="startHour" type="number" min="0" max="23" value="0"></label><label>Trading end hour UTC<input id="endHour" type="number" min="1" max="24" value="24"></label><label>Weekends<select id="weekends"><option value="true">On</option><option value="false">Off</option></select></label><label>Short reference signals<select id="shorts"><option value="false">Off</option><option value="true">On</option></select></label><label>Regime filter<select id="regime"><option value="false">Off</option><option value="true">On</option></select></label>
</div><div class="actions"><button class="btn go" onclick="run(false)">Run baseline</button><button class="btn study" onclick="run(true)">Run baseline + stress + improvements</button><span class="muted" id="note">Official Binance archives are cached locally; the first full run downloads 2018-present.</span></div>
</div></section>
<section class="card" id="summary" hidden><div class="head">Baseline truth table</div><div class="body"><div class="stats" id="stats"></div><div class="legend"><span><i class="sw" style="background:#3aa0ff"></i>Balance</span><span><i class="sw" style="background:#19c37d"></i>Equity</span><span><i class="sw" style="background:#a78bfa"></i>Floating P&amp;L (right scale)</span></div><svg class="chart" id="chart" viewBox="0 0 1200 280" preserveAspectRatio="none"></svg><div id="warnings"></div></div></section>
<div class="grid2"><section class="card" id="worstCard" hidden><div class="head">Worst cycle</div><div class="body" id="worst"></div></section><section class="card" id="levelsCard" hidden><div class="head">Ladder reach and exposure</div><div class="body" id="levelsBody"></div></section></div>
<section class="card" id="stressCard" hidden><div class="head">Crash and detected 30-day stress windows</div><div class="tablewrap" id="stress"></div></section>
<section class="card" id="ideasCard" hidden><div class="head">Ideas tested against the baseline</div><div class="tablewrap" id="ideas"></div></section>
<section class="card" id="sensitivityCard" hidden><div class="head">Trigger sensitivity · $500 to $1,500</div><div class="tablewrap" id="sensitivity"></div></section>
<section class="card" id="capacityCard" hidden><div class="head">Capacity study</div><div class="tablewrap" id="capacity"></div></section>
<section class="card" id="walkCard" hidden><div class="head">Walk-forward and parameter heatmap</div><div class="body" id="walk"></div><div class="tablewrap" id="heat"></div></section>
<section class="card" id="cyclesCard" hidden><div class="head">Cycle ledger</div><div class="tablewrap" id="cycles"></div></section>
<section class="card" id="provCard" hidden><div class="head">Data and execution provenance</div><div class="body"><pre id="provenance"></pre></div></section>
</main><script>
'use strict';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const num=(x,d=2)=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:d});const money=x=>x==null?'—':'$'+num(x,2);
function nullable(id,scale=1){const v=$(id).value.trim();return v===''?null:Number(v)*scale}function values(id){return $(id).value.split(',').map(x=>Number(x.trim())).filter(Number.isFinite)}
function payload(full){return{start:$('start').value,end:$('end').value,full,config:{starting_capital:Number($('capital').value),leverage:Number($('leverage').value),trigger_distance:Number($('trigger').value),ladder_step:Number($('step').value),max_levels:Number($('levels').value),distance_mode:$('distance').value,sizing_mode:$('sizing').value,fixed_ladder_sizes:values('fixed'),level_multipliers:values('multipliers'),auto_btc_per_1000:Number($('auto').value),spread_round_turn_usd:Number($('spread').value),commission_rate:Number($('commission').value),funding_rate_8h:Number($('funding').value),base_slippage_usd:Number($('baseSlip').value),slippage_usd_per_btc:Number($('sizeSlip').value),maintenance_margin_rate:Number($('maintenance').value),profit_target_points:nullable('profit'),max_loss_per_cycle_pct:nullable('loss',.01),max_cycle_duration_hours:nullable('duration'),trading_start_hour_utc:Number($('startHour').value),trading_end_hour_utc:Number($('endHour').value),weekends:$('weekends').value==='true',allow_short_signals:$('shorts').value==='true',regime_filter:$('regime').value==='true'}}}
async function api(path,opt){const r=await fetch(path,opt);const j=await r.json();if(!r.ok||j.ok===false)throw Error(j.error||r.statusText);return j}let timer=null;
async function run(full){$('status').textContent='queueing…';$('note').textContent='The job continues in the background if this page is refreshed.';try{const j=await api('/api/reference-ladder/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(full))});poll(j.job_id)}catch(e){$('status').textContent='failed';$('note').innerHTML='<span class="err">'+esc(e.message)+'</span>'}}
async function poll(id){clearTimeout(timer);try{const j=await api('/api/reference-ladder/jobs/'+encodeURIComponent(id));$('status').textContent=j.status;if(j.status==='complete'){render(j.result);return}if(j.status==='failed')throw Error(j.error);timer=setTimeout(()=>poll(id),2000)}catch(e){$('status').textContent='failed';$('note').innerHTML='<span class="err">'+esc(e.message)+'</span>'}}
function stat(k,v,cls=''){return'<div class="stat"><div class="k">'+esc(k)+'</div><div class="v '+cls+'">'+esc(v)+'</div></div>'}
function table(rows,cols){if(!rows||!rows.length)return'<div class="body muted">No rows.</div>';return'<table><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr>'+rows.map(r=>'<tr>'+cols.map(c=>'<td class="'+(c[2]?c[2](r):'')+'">'+esc(c[1](r))+'</td>').join('')+'</tr>').join('')+'</table>'}
function line(points,key,min,max,w=1200,h=280){const span=max-min||1;return points.map((p,i)=>(i/(points.length-1||1)*w).toFixed(1)+','+(h-(Number(p[key])-min)/span*h).toFixed(1)).join(' ')}
function draw(curve){const svg=$('chart');if(!curve.length){svg.innerHTML='';return}const stride=Math.max(1,Math.floor(curve.length/1000));const pts=curve.filter((_,i)=>i%stride===0||i===curve.length-1);const account=pts.flatMap(p=>[Number(p.balance),Number(p.equity)]),a0=Math.min(...account),a1=Math.max(...account);const floating=pts.map(p=>Number(p.floating_pnl)),f0=Math.min(...floating),f1=Math.max(...floating);svg.innerHTML='<polyline fill="none" stroke="#3aa0ff" stroke-width="2" points="'+line(pts,'balance',a0,a1)+'"/><polyline fill="none" stroke="#19c37d" stroke-width="2" points="'+line(pts,'equity',a0,a1)+'"/><polyline fill="none" stroke="#a78bfa" stroke-width="1.5" opacity=".85" points="'+line(pts,'floating_pnl',f0,f1)+'"/>'}
const perfCols=[['Variant',r=>r.variant||r.period||r.trigger_distance],['Return %',r=>num(r.total_return_pct)],['Final',r=>money(r.final_balance)],['Max equity DD %',r=>num(r.max_equity_drawdown_pct)],['PF',r=>num(r.profit_factor)],['Win %',r=>num(r.win_rate_pct)],['Cycles',r=>num(r.entered_cycles,0)],['Liquidations',r=>num(r.liquidations,0)]];
function render(report){const base=report.baseline;if(!base||!base.ok){$('note').innerHTML='<span class="err">'+esc(base?.error||'Backtest failed')+'</span>';return}const m=base.metrics;$('summary').hidden=false;$('stats').innerHTML=stat('Total return',num(m.total_return_pct)+'%',m.total_return_pct>=0?'pos':'neg')+stat('CAGR',num(m.cagr_pct)+'%')+stat('Profit factor',num(m.profit_factor))+stat('Win rate',num(m.win_rate_pct)+'%')+stat('Sharpe',num(m.sharpe))+stat('Final balance',money(m.final_balance))+stat('Max balance DD',money(m.max_balance_drawdown_usd)+' · '+num(m.max_balance_drawdown_pct)+'%','neg')+stat('Max equity DD',money(m.max_equity_drawdown_usd)+' · '+num(m.max_equity_drawdown_pct)+'%','neg')+stat('Entered cycles',num(m.entered_cycles,0))+stat('Liquidations',num(m.liquidations,0),m.liquidations?'neg':'')+stat('Peak BTC',num(m.peak_exposure_btc,6))+stat('Peak exposure',money(m.peak_exposure_usd));draw(base.curve||[]);$('warnings').innerHTML=(base.warnings||[]).map(x=>'<p class="warn">'+esc(x)+'</p>').join('');
const w=m.worst_cycle;$('worstCard').hidden=false;$('worst').innerHTML=w?'<div class="stats">'+stat('Signal',w.signal_time)+stat('Direction',w.direction)+stat('Deepest float',money(w.deepest_floating_loss_usd)+' · '+num(w.deepest_floating_loss_pct)+'%','neg')+stat('Duration',num(w.duration_hours)+'h')+stat('Levels',w.levels_reached)+stat('Outcome',w.reason,w.liquidated?'neg':(w.recovered?'pos':''))+'</div>':'<span class="muted">No entered cycle.</span>';
$('levelsCard').hidden=false;$('levelsBody').innerHTML='<div class="stats">'+Object.entries(m.level_counts||{}).map(([k,v])=>stat('Reached level '+k,v)).join('')+stat('Exposure / equity',num(m.peak_exposure_vs_equity)+'x')+stat('Execution cost',money(m.total_execution_cost))+stat('Funding cost',money(m.total_funding_cost))+'</div>';
if(report.stress_tests?.length){$('stressCard').hidden=false;$('stress').innerHTML=table(report.stress_tests,[['Period',r=>r.period],['Move %',r=>num(r.move_pct)],['Recovered',r=>r.recovered?'yes':'no'],...perfCols.slice(1),['Deepest float',r=>money(r.deepest_floating_loss_usd)]])}
if(report.improvements?.length){$('ideasCard').hidden=false;$('ideas').innerHTML=table([{variant:'Baseline',...report.baseline_summary},...report.improvements],perfCols)}
if(report.trigger_sensitivity?.length){$('sensitivityCard').hidden=false;$('sensitivity').innerHTML=table(report.trigger_sensitivity,perfCols)}
if(report.capacity?.length){$('capacityCard').hidden=false;$('capacity').innerHTML=table(report.capacity,[['Capital',r=>money(r.starting_capital)],...perfCols.slice(1)])}
if(report.heatmap?.length){$('walkCard').hidden=false;const wf=report.walk_forward||{};$('walk').innerHTML='<p>Chronological 70/30 split: <b>'+esc(wf.split_time||'—')+'</b> · selected trigger: <b>'+esc(wf.selected_trigger_distance??'—')+'</b></p>'+(wf.out_of_sample?'<div class="stats">'+stat('OOS return',num(wf.out_of_sample.total_return_pct)+'%')+stat('OOS max DD',num(wf.out_of_sample.max_equity_drawdown_pct)+'%')+stat('OOS cycles',wf.out_of_sample.entered_cycles)+stat('OOS liquidations',wf.out_of_sample.liquidations)+'</div>':'');$('heat').innerHTML=table(report.heatmap,[['Trigger',r=>r.trigger_distance],['Step',r=>r.ladder_step],...perfCols.slice(1)])}
$('cyclesCard').hidden=false;$('cycles').innerHTML=table((base.cycles||[]).slice().reverse(),[['Signal',r=>r.signal_time],['Side',r=>r.direction],['Levels',r=>r.levels_reached],['Net',r=>money(r.net_pnl)],['Deepest float',r=>money(r.deepest_floating_loss_usd)],['Hours',r=>num(r.duration_hours)],['Reason',r=>r.reason]]);$('provCard').hidden=false;$('provenance').textContent=JSON.stringify(base.provenance,null,2);$('note').textContent='Completed. Results were also saved under output/reference_ladder/latest.json.';$('status').textContent='complete'}
api('/api/reference-ladder/latest').then(j=>{if(j.result)render(j.result)}).catch(()=>{});
</script></body></html>"""
