"""Lucid Strategy Lab page, following the dashboard's inline-page convention."""

LUCID_LAB_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Lucid Strategy Lab</title>
<style>
:root{--bg:#070a0f;--panel:#0c1119;--panel2:#101823;--line:#202d3d;--line2:#33445a;--txt:#dbe6f3;--muted:#8392a7;--amber:#f4bd4a;--green:#35d69f;--red:#fb7185;--blue:#60a5fa;--purple:#c084fc;--mono:ui-monospace,SFMono-Regular,Consolas,monospace;--sans:Inter,Segoe UI,Arial,sans-serif}
*{box-sizing:border-box}html{max-width:100%;background:var(--bg);color:var(--txt);scroll-behavior:smooth;overflow-x:hidden}body{max-width:100%;margin:0;font:14px/1.5 var(--sans);background:radial-gradient(circle at 82% -10%,rgba(244,189,74,.11),transparent 30rem),var(--bg);overflow-x:hidden}
a{color:#8ec5ff}button,input,select{font:inherit}button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:2px solid var(--amber);outline-offset:2px}
.top{position:sticky;top:0;z-index:10;display:flex;align-items:center;gap:10px;min-height:52px;padding:9px 18px;border-bottom:1px solid var(--line);background:rgba(7,10,15,.94);backdrop-filter:blur(14px)}
.brand{font:800 15px var(--mono);letter-spacing:.06em;color:#fff}.brand b{color:var(--amber)}.nav{font:12px var(--mono);text-decoration:none;border:1px solid var(--line2);border-radius:6px;padding:6px 10px;color:var(--muted)}.nav:hover{color:#fff;background:var(--panel2)}.spacer{flex:1}.stamp{font:11px var(--mono);color:var(--muted)}
main{width:100%;max-width:1500px;margin:auto;padding:24px}.hero{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(300px,.7fr);gap:18px;margin-bottom:18px}.hero-main,.hero-side,.card{min-width:0;background:linear-gradient(145deg,rgba(16,24,35,.96),rgba(10,15,23,.96));border:1px solid var(--line);border-radius:12px;box-shadow:0 14px 45px rgba(0,0,0,.25)}
.hero-main{padding:26px;position:relative;overflow:hidden}.hero-main:before{content:"";position:absolute;inset:0 auto auto 0;width:100%;height:2px;background:linear-gradient(90deg,var(--amber),var(--purple),transparent)}
.eyebrow{font:700 11px var(--mono);letter-spacing:.16em;text-transform:uppercase;color:var(--amber)}h1{font:700 clamp(28px,4vw,48px)/1.05 var(--sans);margin:8px 0 12px;letter-spacing:-.035em}.lede{max-width:780px;color:#a8b6c8;font-size:15px}.statusline{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.pill{display:inline-flex;gap:6px;align-items:center;border:1px solid var(--line2);border-radius:999px;padding:5px 9px;font:11px var(--mono);color:#a9b7ca;background:#0a1018}.pill.warn{border-color:#6b4d19;color:#ffd478}.pill.good{border-color:#14563f;color:#78e7bd}.pill.bad{border-color:#6d2936;color:#ff9daf}
.hero-side{padding:18px}.hero-side h2{margin:0 0 14px;font:700 12px var(--mono);text-transform:uppercase;letter-spacing:.12em;color:var(--muted)}.meta{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.6fr);gap:9px;border-bottom:1px solid #182231;padding:8px 0}.meta span:first-child{color:var(--muted)}.meta b{min-width:0;font-family:var(--mono);text-align:right;overflow-wrap:anywhere}
.notice{padding:12px 14px;border:1px solid #664b1e;border-left:3px solid var(--amber);border-radius:8px;background:#1b150b;color:#e8cc91;margin:0 0 18px}.notice strong{color:#ffe0a0}.notice.error{border-color:#742c39;border-left-color:var(--red);background:#1a0d12;color:#ffc0ca}
.card{padding:18px;margin-bottom:18px}.card h2{margin:0;font-size:18px}.card h3{margin:18px 0 8px;font-size:14px}.head{display:flex;align-items:flex-start;gap:12px;margin-bottom:16px}.head .num{font:800 11px var(--mono);color:#12100a;background:var(--amber);border-radius:4px;padding:3px 6px}.head p{margin:3px 0 0;color:var(--muted)}
.controls{display:grid;grid-template-columns:repeat(6,minmax(145px,1fr));gap:12px}.field{display:flex;flex-direction:column;gap:5px}.field label{font:700 10px var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}.field input,.field select{width:100%;border:1px solid var(--line2);border-radius:6px;background:#090e15;color:var(--txt);padding:9px}.field small{color:#64748b}.check{justify-content:end}.check label{display:flex;gap:8px;align-items:center;min-height:39px;text-transform:none;font-size:12px}.check input{width:auto}
.metrics{display:grid;grid-template-columns:repeat(6,minmax(120px,1fr));gap:10px}.metric{min-height:86px;padding:12px;border:1px solid #1e2b3a;border-radius:8px;background:#090e15}.metric .k{font:700 10px var(--mono);color:var(--muted);text-transform:uppercase;letter-spacing:.07em}.metric .v{font:800 21px var(--mono);margin-top:6px}.metric .s{font-size:11px;color:#6f8097;margin-top:4px}.metric.good .v{color:var(--green)}.metric.warn .v{color:var(--amber)}.metric.bad .v{color:var(--red)}
.rule-grid,.instruction-grid,.chart-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.rule,.instruction{padding:13px;border:1px solid #1e2b3a;border-radius:8px;background:#090e15}.rule .label,.instruction .sleeve{font:700 10px var(--mono);color:var(--muted);text-transform:uppercase;letter-spacing:.07em}.rule .value{font:800 16px var(--mono);margin:5px 0}.source{display:block;font-size:11px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tag{display:inline-block;border:1px solid #365069;border-radius:4px;padding:1px 5px;font:9px var(--mono);color:#9cc4e8;margin-left:4px}.tag.estimated{border-color:#72551e;color:#f6cf76}.tag.disputed{border-color:#7c2f3c;color:#ff9dad}
.instruction{border-top:2px solid var(--blue)}.instruction p{margin:8px 0;color:#aab7c7}.instruction b{color:#e5edf7}.formula{font:12px/1.7 var(--mono);background:#070b10;border:1px dashed #34445a;border-radius:7px;padding:12px;color:#b8c6d8}
.calc{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(320px,.85fr);gap:16px}.calc-inputs{display:grid;grid-template-columns:repeat(3,minmax(120px,1fr));gap:10px}.calc-result{border:1px solid #2c4259;border-radius:9px;background:#08101a;padding:16px}.quantity{font:900 50px/1 var(--mono);color:var(--green);margin:8px 0}.btn{border:1px solid var(--amber);border-radius:6px;background:#211807;color:#ffd985;padding:9px 14px;font:700 12px var(--mono);cursor:pointer}.btn:hover{background:#2e2109}.btn.secondary{border-color:var(--line2);background:#0b1119;color:#b7c6d8}.btn.danger{border-color:#703242;background:#1d0c12;color:#ffadba}.btn:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.progress{height:7px;flex:1;min-width:150px;background:#182230;border-radius:99px;overflow:hidden}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--amber),var(--green));width:0;transition:width .2s}
.plan{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.plan-step{border-left:2px solid var(--amber);padding:4px 12px}.plan-step b{font:700 11px var(--mono);color:var(--amber);text-transform:uppercase}.plan-step ul{padding-left:17px;color:#9eacc0}.plan-step li{margin:6px 0}
.table-wrap{width:100%;max-width:100%;overflow:auto;border:1px solid var(--line);border-radius:8px}table{width:100%;border-collapse:collapse;min-width:760px;background:#090e15}th,td{text-align:left;border-bottom:1px solid #192434;padding:9px 11px;vertical-align:top}th{position:sticky;top:0;background:#101823;color:#8494aa;font:700 10px var(--mono);letter-spacing:.06em;text-transform:uppercase}td.num{text-align:right;font-family:var(--mono)}tr:last-child td{border-bottom:0}.selected-row{background:rgba(53,214,159,.06)}
.chart{min-height:250px;padding:12px;border:1px solid #1d2a39;border-radius:8px;background:#080d14}.chart h3{font:700 11px var(--mono);text-transform:uppercase;color:#9aabc0;margin:0 0 6px}.chart svg{width:100%;height:170px;display:block;overflow:visible}.chart-summary{font-size:11px;color:#78899f}.bars{height:170px;display:flex;align-items:flex-end;gap:5px;border-bottom:1px solid #334155;padding:8px}.bar{flex:1;min-width:5px;background:linear-gradient(var(--green),#176b53);border-radius:3px 3px 0 0;position:relative}.bar:hover:after{content:attr(data-tip);position:absolute;bottom:100%;left:50%;transform:translateX(-50%);background:#101827;border:1px solid var(--line2);padding:4px 6px;white-space:nowrap;font:10px var(--mono);z-index:3}.legend{display:flex;gap:12px;flex-wrap:wrap;font:10px var(--mono);color:var(--muted)}.legend i{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:4px}
.method{columns:2;column-gap:28px}.method p,.method li{color:#9baabd}.method h3{break-after:avoid}.source-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.source-item{padding:9px;border:1px solid #1e2a39;border-radius:6px;background:#090e15}.source-item a{font-weight:700}.source-item small{display:block;color:#718198;margin-top:3px}
.upload{display:flex;align-items:end;gap:10px;flex-wrap:wrap}.upload .field{min-width:240px;flex:1}.empty{padding:24px;text-align:center;color:var(--muted);border:1px dashed var(--line2);border-radius:8px}.skeleton{height:80px;border-radius:8px;background:linear-gradient(90deg,#0c121b,#172231,#0c121b);background-size:220% 100%;animation:pulse 1.3s linear infinite}@keyframes pulse{to{background-position:-220% 0}}
footer{max-width:1500px;margin:0 auto;padding:8px 24px 40px;color:#627086;font-size:11px}
@media(max-width:1120px){.hero{grid-template-columns:1fr}.controls{grid-template-columns:repeat(3,1fr)}.metrics{grid-template-columns:repeat(3,1fr)}.plan{grid-template-columns:repeat(2,1fr)}}
@media(max-width:820px){main{padding:14px}.top{flex-wrap:wrap}.stamp{display:none}.rule-grid,.instruction-grid,.chart-grid{grid-template-columns:1fr}.calc{grid-template-columns:1fr}.controls,.calc-inputs{grid-template-columns:repeat(2,1fr)}.method{columns:1}.source-list{grid-template-columns:1fr}}
@media(max-width:560px){.hero-main{padding:18px}.controls,.calc-inputs,.metrics,.plan{grid-template-columns:minmax(0,1fr)}.metric{min-height:72px}.top{padding:8px 10px}.brand{width:100%}.card{padding:14px}.quantity{font-size:40px}.hero-side .meta{grid-template-columns:1fr;gap:2px}.hero-side .meta b{text-align:left}.notice,h1,.lede,.formula{overflow-wrap:anywhere}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.skeleton{animation:none}.progress i{transition:none}}
</style>
</head>
<body>
<nav class="top" aria-label="Primary">
  <span class="brand"><b>LUCID</b> STRATEGY LAB</span>
  <a class="nav" href="/">← Chart</a><a class="nav" href="/paper">Paper Trading</a>
  <span class="spacer"></span><span class="stamp" id="topstamp">loading verified rules…</span>
</nav>
<main>
  <section class="hero" aria-labelledby="page-title">
    <div class="hero-main"><div class="eyebrow">Rule-aware futures evaluation research</div><h1 id="page-title">A pass plan measured against the account—not a pretty P&amp;L chart.</h1><p class="lede">Compare current Lucid programs, calculate actual stop risk, inspect chronological rolling evaluations, and see exactly how the strongest surviving candidate degrades under worse execution.</p><div class="statusline" id="statusline"><span class="pill">loading evidence…</span></div></div>
    <aside class="hero-side" aria-label="Research metadata" id="hero-meta"><div class="skeleton"></div></aside>
  </section>
  <div class="notice" id="truth">Loading the source-stamped validation artifact…</div>

  <section class="card" id="account-section"><div class="head"><span class="num">01</span><div><h2>Account and evidence scope</h2><p>Only combinations supported by verified rule configuration are selectable. Changing program does not relabel the same backtest as valid.</p></div></div><div class="controls">
    <div class="field"><label for="program">Program</label><select id="program"></select></div>
    <div class="field"><label for="stage">Stage</label><select id="stage"><option value="evaluation">Evaluation</option></select></div>
    <div class="field"><label for="size">Account size</label><select id="size"></select></div>
    <div class="field"><label for="instrument">Contract</label><select id="instrument"><option>MNQ</option><option>MES</option><option>MCL</option><option>NQ</option><option>ES</option><option>CL</option></select></div>
    <div class="field"><label for="horizon">Evaluation horizon</label><select id="horizon"><option value="20">20 sessions</option><option value="30">30 sessions</option><option value="45" selected>45 sessions</option></select></div>
    <div class="field"><label for="preset">Execution stress</label><select id="preset"></select></div>
    <div class="field" id="drawdown-wrap"><label for="drawdown">Evaluation drawdown</label><select id="drawdown"><option value="eod">End of day</option><option value="intraday">Intraday</option></select></div>
    <div class="field check" id="dll-wrap"><label><input type="checkbox" id="dll" checked> Daily loss limit enabled</label></div>
  </div><div id="scope-note" class="notice" style="margin-top:14px"></div></section>

  <section class="card"><div class="head"><span class="num">02</span><div><h2>Official rule summary</h2><p>Values include program, stage, source date and confidence. Estimated execution is never shown as a Lucid rule.</p></div></div><div class="rule-grid" id="rule-grid"><div class="skeleton"></div></div><h3>Prohibited and operational behavior</h3><div class="formula" id="behavior"></div></section>

  <section class="card"><div class="head"><span class="num">03</span><div><h2>Selected experimental strategy</h2><p>Every setup is measurable. Signals wait for completed bars and enter on the next minute.</p></div></div><div class="instruction-grid" id="instructions"></div><h3>Portfolio risk rules</h3><div class="formula" id="portfolio-rules"></div></section>

  <section class="card"><div class="head"><span class="num">04</span><div><h2>Position-size calculator</h2><p>Quantity is limited by remaining MLL/DLL room, stop risk, execution cost, safety reserve and the Lucid cap.</p></div></div><div class="calc"><div class="calc-inputs">
    <div class="field"><label for="current">Current balance</label><input id="current" type="number" step="0.01"></div>
    <div class="field"><label for="floor">Drawdown floor</label><input id="floor" type="number" step="0.01"></div>
    <div class="field"><label for="daily-room">Daily loss remaining</label><input id="daily-room" type="number" step="0.01" placeholder="not applicable"></div>
    <div class="field"><label for="stop-ticks">Stop distance (ticks)</label><input id="stop-ticks" type="number" min="1" step="1" value="40"></div>
    <div class="field"><label for="risk-budget">Selected risk budget</label><input id="risk-budget" type="number" min="1" step="1" value="400"></div>
    <div class="field"><label for="reserve">Safety reserve</label><input id="reserve" type="number" min="0" step="1" value="100"></div>
    <div class="field"><label for="open-cap">Open micro equivalents</label><input id="open-cap" type="number" min="0" step="1" value="0"></div>
    <div class="actions"><button class="btn" id="calc-btn">Calculate size</button></div>
  </div><div class="calc-result" id="calc-result"><div class="empty">Enter the current account values, then calculate.</div></div></div></section>

  <section class="card"><div class="head"><span class="num">05</span><div><h2>Daily operating plan</h2><p>Generated from the selected strategy and active account rules.</p></div></div><div class="plan" id="daily-plan"></div></section>

  <section class="card"><div class="head"><span class="num">06</span><div><h2>Chronological backtest</h2><p id="backtest-caption">All rolling starts remain in the denominator, including no-trade days.</p></div></div><div class="metrics" id="backtest-metrics"></div><h3>Development / validation / chronological test</h3><div class="table-wrap"><table><thead><tr><th>Split</th><th>Windows</th><th>Pass</th><th>Breach</th><th>Unfinished</th><th>Median pass*</th><th>Worst DD</th></tr></thead><tbody id="split-table"></tbody></table></div><small>* Conditional on passing. Restricted-mean duration is shown in the metric details.</small></section>

  <section class="card"><div class="head"><span class="num">07</span><div><h2>Execution stress tests</h2><p>Every row replays the full 45-session account path; the severe case combines worse costs, stop fills and missed trades.</p></div></div><div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Windows</th><th>Pass</th><th>Breach</th><th>Unfinished</th><th>Median pass*</th><th>Worst drawdown</th></tr></thead><tbody id="stress-table"></tbody></table></div><div class="actions"><button class="btn" id="replay-btn">Run reproducible replay</button><button class="btn danger" id="cancel-btn" disabled>Cancel</button><div class="progress" aria-label="Simulation progress"><i id="progress"></i></div><span class="stamp" id="run-state">idle</span></div></section>

  <section class="card"><div class="head"><span class="num">08</span><div><h2>Research charts</h2><p>Charts include accessible summaries and use no external library.</p></div></div><div class="chart-grid">
    <div class="chart"><h3>Representative equity path</h3><svg id="equity-chart" role="img"></svg><p class="chart-summary" id="equity-summary"></p></div>
    <div class="chart"><h3>Drawdown room</h3><svg id="drawdown-chart" role="img"></svg><p class="chart-summary" id="drawdown-summary"></p></div>
    <div class="chart"><h3>Rolling pass probability</h3><svg id="rolling-chart" role="img"></svg><p class="chart-summary" id="rolling-summary"></p></div>
    <div class="chart"><h3>Pass-time distribution</h3><div class="bars" id="duration-bars" role="img"></div><p class="chart-summary" id="duration-summary"></p></div>
    <div class="chart"><h3>Terminal profit distribution</h3><div class="bars" id="terminal-bars" role="img"></div><p class="chart-summary" id="terminal-summary"></p></div>
    <div class="chart"><h3>Modeled cost breakdown</h3><div class="bars" id="cost-bars" role="img"></div><p class="chart-summary" id="cost-summary"></p></div>
  </div></section>

  <section class="card"><div class="head"><span class="num">09</span><div><h2>Rule-compliance timeline</h2><p>A representative historical path near the conditional median—not a cherry-picked best curve.</p></div></div><div class="table-wrap"><table><thead><tr><th>Day</th><th>Session</th><th>Start</th><th>End</th><th>Daily net</th><th>MLL floor</th><th>Room</th><th>Cap</th><th>Status</th></tr></thead><tbody id="timeline"></tbody></table></div></section>

  <section class="card"><div class="head"><span class="num">10</span><div><h2>Strategy comparison</h2><p>The selected portfolio ranks on robustness, frequency and rule compliance—not the highest isolated P&amp;L.</p></div></div><div class="table-wrap"><table><thead><tr><th>Candidate</th><th>Instrument</th><th>Trades</th><th>Windows</th><th>Expectancy</th><th>PF</th><th>Pass</th><th>Severe pass</th><th>Status / reason</th></tr></thead><tbody id="candidates"></tbody></table></div><h3>Parameter sensitivity</h3><div class="chart"><div class="bars" id="sensitivity-bars" role="img"></div><p class="chart-summary" id="sensitivity-summary"></p></div></section>

  <section class="card"><div class="head"><span class="num">11</span><div><h2>Data import validator</h2><p>CSV and Parquet validation checks timestamps, timezone, ordering, duplicates, gaps, OHLC, volume, symbol and expiry metadata. Uploaded files are temporary and not retained.</p></div></div><form class="upload" id="upload-form"><div class="field"><label for="data-file">Market data file</label><input id="data-file" type="file" accept=".csv,.parquet,.pq" required></div><div class="field"><label for="data-symbol">Expected symbol</label><input id="data-symbol" value="MNQ" required></div><button class="btn secondary" type="submit">Validate only</button></form><div id="upload-result" class="empty" style="margin-top:12px">No file selected. This validator never adds uploaded data to the evidence artifact.</div></section>

  <section class="card"><div class="head"><span class="num">12</span><div><h2>Sources, conflicts and methodology</h2><p>Official rules are linked directly. Model assumptions and unresolved conflicts remain visible.</p></div></div><div class="method" id="methodology"></div><h3>Official sources used by the active configuration</h3><div class="source-list" id="sources"></div></section>
</main>
<footer id="footer">Lucid Strategy Lab is read-only research software. It cannot place an order or guarantee an evaluation outcome.</footer>
<script>
'use strict';
const $=id=>document.getElementById(id); let state=null,activeJob=null,pollTimer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v));
const pct=v=>v==null?'—':(Number(v)*100).toFixed(1)+'%'; const num=v=>v==null?'—':Number(v).toLocaleString();
function query(){return new URLSearchParams({program:$('program').value||'lucidpro',stage:'evaluation',size:$('size').value||'25000',daily_drawdown:$('drawdown').value,daily_loss_enabled:$('dll').checked?'true':'false'}).toString()}
async function getJSON(url,opts){const r=await fetch(url,opts);let j;try{j=await r.json()}catch(e){throw new Error('Server returned non-JSON response')}if(!r.ok||j.ok===false)throw new Error(j.error||('HTTP '+r.status));return j}
function programChanged(){if(!state)return;const p=state.program_options.find(x=>x.id===$('program').value);$('size').innerHTML=p.sizes.map(v=>`<option value="${v}">${money(v).replace('.00','')}</option>`).join('');$('drawdown-wrap').style.display=p.id==='luciddaily'?'flex':'none';$('dll-wrap').style.display=(p.id==='luciddaily'||p.id==='lucidpro')?'flex':'none';loadSnapshot()}
async function loadSnapshot(){try{$('truth').className='notice';$('truth').textContent='Loading verified rules and the source-stamped evidence artifact…';state=await getJSON('/api/lucid-lab/snapshot?'+query());render()}catch(e){$('truth').className='notice error';$('truth').textContent='Lucid Lab could not load: '+e.message}}
function initControls(){const currentProgram=$('program').value||'lucidpro';$('program').innerHTML=state.program_options.map(p=>`<option value="${p.id}">${esc(p.label)}</option>`).join('');$('program').value=currentProgram;const p=state.program_options.find(x=>x.id===currentProgram)||state.program_options[0];const currentSize=$('size').value||String(state.account.account_size);$('size').innerHTML=p.sizes.map(v=>`<option value="${v}">${money(v).replace('.00','')}</option>`).join('');$('size').value=p.sizes.includes(Number(currentSize))?currentSize:String(p.sizes[0]);$('preset').innerHTML=state.execution_presets.map(p=>`<option value="${p.key}">${esc(p.label)}</option>`).join('');$('preset').value=$('preset').dataset.keep||'normal';$('drawdown-wrap').style.display=p.id==='luciddaily'?'flex':'none';$('dll-wrap').style.display=(p.id==='luciddaily'||p.id==='lucidpro')?'flex':'none'}
function render(){initControls();const e=state.evidence,a=state.account,s=e.selected,d=e.data;$('topstamp').textContent='rules checked '+state.rules_last_checked+' · run '+e.run_id;$('statusline').innerHTML=`<span class="pill warn">${esc(e.status_label)}</span><span class="pill">${esc(s.strategy_version)}</span><span class="pill">run ${esc(e.run_id)}</span><span class="pill">no live trading</span>`;$('hero-meta').innerHTML=`<h2>Research snapshot</h2>${[['Strategy',s.strategy_version],['Rules verified',state.rules_last_checked],['Data',d.test_start+' → '+d.test_end],['Program',s.program+' '+money(s.account_size).replace('.00','')],['Instrument',s.instrument],['Simulation',e.generated_at]].map(x=>`<div class="meta"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('')}`;$('truth').innerHTML=`<strong>${esc(e.status_label)}.</strong> ${esc(state.disclaimer)} ${esc(s.limitations[0])}`;$('scope-note').className='notice'+(state.evidence_applies?'':' error');$('scope-note').textContent=state.evidence_scope_note;renderRules();renderInstructions();setCalculatorDefaults();renderPlan();renderBacktest();renderStress();renderCharts();renderTimeline();renderCandidates();renderMethod()}
function sourceFor(i=0){return state.account.sources[i]||state.account.sources[0]}
function rule(label,value,source,tag='verified',note=''){return `<div class="rule"><div class="label">${esc(label)} <span class="tag ${tag}">${esc(tag)}</span></div><div class="value">${esc(value)}</div>${note?`<div>${esc(note)}</div>`:''}<a class="source" href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.title)} · ${esc(source.displayed_date)}</a></div>`}
function renderRules(){const a=state.account,src=sourceFor(0),dd=sourceFor(1),prod=a.sources.find(x=>x.title.includes('Products'))||src;$('rule-grid').innerHTML=[rule('Profit target',money(a.profit_target),src),rule('Maximum loss',money(a.max_loss),dd),rule('Drawdown',a.drawdown_type.toUpperCase()+' trailing',dd),rule('Daily loss limit',a.daily_loss_limit?money(a.daily_loss_limit)+' soft stop':'None',src),rule('Consistency',a.consistency_limit_pct?a.consistency_limit_pct+'% (strict; cushion ignored)':'None in evaluation',src,a.consistency_limit_pct?'disputed':'verified'),rule('Maximum contracts',a.max_minis+' minis or '+a.max_micros+' micros',src),rule('Minimum days',String(a.minimum_trading_days),src),rule('Official cutoff',a.forced_close_ny+' New York',sourceFor(a.sources.length-2),a.conflicts.length?'disputed':'verified','Strategy exits by 16:00.'),rule('Overnight / weekend','Not modeled; flat intraday',sourceFor(a.sources.length-2)),rule('MNQ/MES/MCL commission','$0.50 per side',prod),rule('News rule',a.news_rule,src,a.program_id==='luciddaily'?'verified':'estimated'),rule('Trail lock',money(a.locked_floor)+' after > '+money(a.trail_trigger),dd)].join('');$('behavior').innerHTML=`No martingale · no averaging recovery · no cross-account hedging · no HFT · no simulated-fill exploitation · no microscalping · aggregate mini/micro cap enforced.<br>${a.conflicts.map(x=>'⚠ '+esc(x)).join('<br>')||'No unresolved program-specific conflict changes this simulation.'}`}
function renderInstructions(){const s=state.evidence.selected;$('instructions').innerHTML=state.evidence.strategy_rules.map(r=>`<article class="instruction"><div class="sleeve">${esc(r.sleeve)}</div><p><b>Setup:</b> ${esc(r.setup)}</p><p><b>Entry:</b> ${esc(r.entry)}</p><p><b>Stop:</b> ${esc(r.stop)}</p><p><b>Target:</b> ${esc(r.target)}</p></article>`).join('');$('portfolio-rules').innerHTML=`Morning sleeve budget ${money(s.morning_risk_usd)} · prior-range budget ${money(s.prior_breakout_risk_usd)} · ${s.maximum_trades_per_day} trades/day maximum · stop after ${s.maximum_losing_trades_per_day} losing trades · daily profit lock ${money(s.daily_profit_lock_usd)} · safety reserve ${money(s.safety_reserve_usd)} · force flat ${esc(s.forced_close_ny)} NY.<br>No trade: stale/incomplete session, unrecognized roll, size below one micro, insufficient MLL/DLL room, spread stress above preset, or ${esc(s.event_filter)}`}
function setCalculatorDefaults(){const a=state.account,s=state.evidence.selected;$('current').value=a.starting_balance;$('floor').value=Number(a.starting_balance)-Number(a.max_loss);$('daily-room').value=a.daily_loss_limit||'';$('risk-budget').value=Number(a.account_size)===25000?s.morning_risk_usd:Math.round(Number(a.max_loss)*.4);$('reserve').value=s.safety_reserve_usd}
async function calculate(){const body={program:$('program').value,stage:'evaluation',account_size:Number($('size').value),daily_drawdown:$('drawdown').value,daily_loss_enabled:$('dll').checked,instrument:$('instrument').value,current_balance:$('current').value,drawdown_floor:$('floor').value,daily_loss_remaining:$('daily-room').value,stop_ticks:$('stop-ticks').value,risk_budget:$('risk-budget').value,safety_reserve:$('reserve').value,open_micro_equivalents:$('open-cap').value,execution_preset:$('preset').value};try{$('calc-result').innerHTML='<div class="skeleton"></div>';const j=await getJSON('/api/lucid-lab/position-size',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),r=j.result;$('calc-result').innerHTML=`<div class="eyebrow">Final allowed quantity</div><div class="quantity">${r.final_quantity}</div><div class="meta"><span>Risk / contract</span><b>${money(r.risk_per_contract)}</b></div><div class="meta"><span>Max by account cap</span><b>${r.maximum_by_account_cap}</b></div><div class="meta"><span>Max by risk</span><b>${r.maximum_by_risk}</b></div><div class="meta"><span>Expected execution cost</span><b>${money(r.expected_cost)}</b></div><div class="meta"><span>Loss if stopped</span><b>${money(r.loss_if_stopped)}</b></div><div class="meta"><span>Buffer after stop</span><b>${money(r.remaining_buffer_after_stop)}</b></div><p class="chart-summary">Binding constraint: ${esc(r.binding_constraint)}${r.warnings.length?' · '+esc(r.warnings.join(' ')):''}</p>`}catch(e){$('calc-result').innerHTML=`<div class="notice error">${esc(e.message)}</div>`}}
function renderPlan(){$('daily-plan').innerHTML=state.daily_plan.map(p=>`<div class="plan-step"><b>${esc(p.phase)}</b><ul>${p.checks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`).join('')}
function activeHorizon(){return state.evidence.horizons[$('horizon').value]||state.evidence.horizons['45']}
function renderBacktest(){const e=state.evidence,r=activeHorizon(),t=e.trade_statistics,applies=state.evidence_applies;$('backtest-caption').textContent=(applies?'Evidence applies to the selected LucidPro EOD configuration. ':'Reference evidence only for this selection. ')+'Real proxy data '+e.data.test_start+' through '+e.data.test_end+'; all rolling starts remain in the denominator.';const items=[['Pass probability',applies?pct(r.pass_rate):'scope mismatch','Wilson '+pct(r.pass_wilson_95[0])+'–'+pct(r.pass_wilson_95[1]),'good'],['Breach probability',applies?pct(r.breach_rate):'scope mismatch',r.breaches+' paths','warn'],['Unfinished',applies?pct(r.unfinished_rate):'scope mismatch',r.unfinished+' paths','warn'],['Median to pass*',r.duration.median?r.duration.median+' sessions':'—','P10 '+r.duration.p10+' · P90 '+r.duration.p90,''],['Test trades',num(t.trades),'from '+e.data.test_trades_raw+' raw signals',''],['Net expectancy',money(t.expectancy),'standalone sized trade','good'],['Profit factor',t.profit_factor,'after modeled costs',''],['Worst path drawdown',money(r.worst_max_drawdown),'EOD trail differs from peak DD','bad'],['Commission',money(t.commissions),'official per-side rate',''],['Spread cost',money(t.spread_cost),'modeled',''],['Slippage cost',money(t.slippage_cost),'modeled',''],['Costs / gross',t.cost_pct_of_positive_gross+'%','commission + spread + slippage','']];$('backtest-metrics').innerHTML=items.map(x=>`<div class="metric ${x[3]}"><div class="k">${esc(x[0])}</div><div class="v">${esc(x[1])}</div><div class="s">${esc(x[2])}</div></div>`).join('');$('split-table').innerHTML=Object.entries(e.split_results).map(([k,v])=>`<tr><td>${esc(k.replaceAll('_',' '))}</td><td class="num">${num(v.windows)}</td><td class="num">${pct(v.pass_rate)}</td><td class="num">${pct(v.breach_rate)}</td><td class="num">${pct(v.unfinished_rate)}</td><td class="num">${v.duration.median??'—'}</td><td class="num">${money(v.worst_max_drawdown)}</td></tr>`).join('')}
function renderStress(){$('stress-table').innerHTML=state.evidence.stresses.map(r=>`<tr class="${r.id===$('preset').value?'selected-row':''}"><td>${esc(r.label)}${r.selection?`<br><small>${esc(r.selection)}</small>`:''}</td><td class="num">${num(r.windows)}</td><td class="num">${pct(r.pass_rate)}</td><td class="num">${pct(r.breach_rate)}</td><td class="num">${pct(r.unfinished_rate)}</td><td class="num">${r.duration?.median??'—'}</td><td class="num">${money(r.worst_max_drawdown)}</td></tr>`).join('')}
function lineChart(id,values,fn,color,label){const svg=$(id);if(!values.length){svg.innerHTML='';svg.setAttribute('aria-label','No '+label+' data');return}const w=600,h=160,p=12,ys=values.map(fn),lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1,pts=ys.map((v,i)=>`${p+i*(w-2*p)/Math.max(1,ys.length-1)},${h-p-(v-lo)*(h-2*p)/span}`).join(' ');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('aria-label',`${label}: minimum ${lo.toFixed(2)}, maximum ${hi.toFixed(2)}, ${values.length} observations`);svg.innerHTML=`<line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#334155"/><polyline fill="none" stroke="${color}" stroke-width="3" points="${pts}"/><circle cx="${pts.split(' ').at(-1).split(',')[0]}" cy="${pts.split(' ').at(-1).split(',')[1]}" r="4" fill="${color}"/>`}
function bars(id,rows,value,label){const box=$(id),max=Math.max(1,...rows.map(value));box.setAttribute('aria-label',label);box.innerHTML=rows.map(r=>`<div class="bar" style="height:${Math.max(2,value(r)/max*100)}%" data-tip="${esc(r.name??r.days??(money(r.lo)+'–'+money(r.hi)))}: ${esc(value(r))}"></div>`).join('')}
function renderCharts(){const c=state.evidence.charts,t=c.representative_timeline;lineChart('equity-chart',t,x=>Number(x.ending_balance),'#35d69f','Representative ending balance');lineChart('drawdown-chart',t,x=>Number(x.remaining_drawdown),'#fb7185','Remaining drawdown room');lineChart('rolling-chart',c.rolling_pass_probability,x=>Number(x.pass_rate)*100,'#f4bd4a','Rolling pass probability percent');$('equity-summary').textContent=t.length?`Starts ${money(t[0].starting_balance)} and ends ${money(t.at(-1).ending_balance)} after ${t.length} sessions.`:'No representative path.';$('drawdown-summary').textContent=t.length?`Minimum displayed remaining room ${money(Math.min(...t.map(x=>x.remaining_drawdown)))}.`:'No drawdown path.';$('rolling-summary').textContent=`${c.rolling_pass_probability.length} chronological blocks; this exposes regime variation.`;bars('duration-bars',c.pass_duration_histogram,x=>x.count,'Conditional pass-time histogram');$('duration-summary').textContent='Successful paths only; non-passes are not silently treated as missing.';bars('terminal-bars',c.terminal_profit_histogram,x=>x.count,'Historical terminal profit histogram');$('terminal-summary').textContent=`Monte Carlo median ${money(state.evidence.monte_carlo.terminal_profit_median)}; 5th percentile ${money(state.evidence.monte_carlo.terminal_profit_p05)}.`;bars('cost-bars',c.cost_breakdown,x=>Number(x.value),'Modeled cost breakdown');$('cost-summary').textContent=c.cost_breakdown.map(x=>x.name+' '+money(x.value)).join(' · ')}
function renderTimeline(){$('timeline').innerHTML=state.evidence.charts.representative_timeline.map(r=>`<tr><td>${r.day}</td><td>${esc(r.session)}</td><td class="num">${money(r.starting_balance)}</td><td class="num">${money(r.ending_balance)}</td><td class="num">${money(r.daily_net_pnl)}</td><td class="num">${money(r.drawdown_floor)}</td><td class="num">${money(r.remaining_drawdown)}</td><td class="num">${r.permitted_micros}µ</td><td>${esc(r.status)}${r.warning?'<br><small>'+esc(r.warning)+'</small>':''}</td></tr>`).join('')}
function renderCandidates(){const e=state.evidence;$('candidates').innerHTML=e.candidates.map(r=>`<tr class="${r.id==='selected_portfolio'?'selected-row':''}"><td><b>${esc(r.name)}</b></td><td>${esc(r.instrument)}</td><td class="num">${num(r.trades)}</td><td class="num">${num(r.windows)}</td><td class="num">${money(r.net_expectancy)}</td><td class="num">${r.profit_factor??'—'}</td><td class="num">${pct(r.normal_pass_rate)}</td><td class="num">${pct(r.stressed_pass_rate)}</td><td><span class="tag ${r.validation_status==='INVALIDATED'?'disputed':''}">${esc(r.validation_status)}</span><br><small>${esc(r.reason)}</small></td></tr>`).join('');const rows=e.sensitivity.filter(x=>x.prior_risk===100);bars('sensitivity-bars',rows,x=>Number(x.pass_rate)*100,'Pass probability across morning risk sensitivity');$('sensitivity-summary').textContent=rows.map(x=>money(x.morning_risk)+' → '+pct(x.pass_rate)+' pass / '+pct(x.breach_rate)+' breach').join(' · ')}
function renderMethod(){const e=state.evidence,m=e.methodology,mc=e.monte_carlo,rc=e.risk_controls;$('methodology').innerHTML=`<h3>Data and splits</h3><p>${esc(e.data.source)}. ${esc(m.development)}; validation ${esc(m.validation)}; chronological test ${esc(m.test)}. ${esc(m.selection_warning)}</p><h3>Execution</h3><p>${esc(m.fill)}. ${esc(m.commission)}. Spread and slippage are conservative configurable estimates.</p><h3>Uncertainty</h3><p>${esc(m.uncertainty)}. Block-bootstrap pass range ${pct(e.horizons['45'].pass_block_bootstrap_95[0])}–${pct(e.horizons['45'].pass_block_bootstrap_95[1])}. Monte Carlo ${num(mc.paths)} paths: ${pct(mc.pass_rate)} pass, ${pct(mc.breach_rate)} breach, ${pct(mc.unfinished_rate)} unfinished. ${esc(mc.warning)}</p><h3>Risk controls observed</h3><p>${num(rc.risk_rejections)} entry rejections, ${num(rc.contract_cap_limits)} cap limits and ${num(rc.daily_loss_blocks)} DLL blocks across overlapping rolling paths; ${num(rc.historical_gap_through_stops_in_raw_test_signals)} raw signals had historical gap-through stops.</p><h3>Known conflicts</h3><p>${state.account.conflicts.length?state.account.conflicts.map(esc).join(' '):'No unresolved conflict changes the active Pro evaluation model.'} The exact consistency cushion is ignored in favor of the stricter headline ratio.</p>`;$('sources').innerHTML=state.account.sources.map(s=>`<div class="source-item"><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a><small>Displayed ${esc(s.displayed_date)} · retrieved ${esc(s.retrieved_at)}</small></div>`).join('')}
async function startReplay(){try{const j=await getJSON('/api/lucid-lab/simulations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({execution_preset:$('preset').value,account_size:Number($('size').value)})});activeJob=j.id;$('cancel-btn').disabled=false;pollReplay()}catch(e){$('run-state').textContent='error: '+e.message}}
async function pollReplay(){if(!activeJob)return;try{const j=await getJSON('/api/lucid-lab/simulations/'+encodeURIComponent(activeJob));$('progress').style.width=j.progress+'%';$('run-state').textContent=j.status+' · '+j.progress+'%';if(['completed','error','cancelled'].includes(j.status)){$('cancel-btn').disabled=true;activeJob=null;return}pollTimer=setTimeout(pollReplay,150)}catch(e){$('run-state').textContent='error: '+e.message}}
async function cancelReplay(){if(!activeJob)return;clearTimeout(pollTimer);await fetch('/api/lucid-lab/simulations/'+encodeURIComponent(activeJob)+'/cancel',{method:'POST'});$('run-state').textContent='cancelled';$('cancel-btn').disabled=true;activeJob=null}
async function validateUpload(ev){ev.preventDefault();const file=$('data-file').files[0];if(!file)return;const form=new FormData();form.append('file',file);$('upload-result').className='empty';$('upload-result').textContent='Validating…';try{const j=await getJSON('/api/lucid-lab/validate-data?symbol='+encodeURIComponent($('data-symbol').value),{method:'POST',body:form});const r=j.report;$('upload-result').className=r.ok?'notice':'notice error';$('upload-result').textContent=(r.ok?'Valid':'Rejected')+`: ${r.rows} rows, ${r.first_timestamp||'—'} → ${r.last_timestamp||'—'}, ${r.missing_intervals} gaps. `+[...r.errors,...r.warnings].join(' ')}catch(e){$('upload-result').className='notice error';$('upload-result').textContent=e.message}}
$('program').addEventListener('change',programChanged);$('size').addEventListener('change',loadSnapshot);$('drawdown').addEventListener('change',loadSnapshot);$('dll').addEventListener('change',loadSnapshot);$('horizon').addEventListener('change',()=>{renderBacktest()});$('preset').addEventListener('change',()=>{$('preset').dataset.keep=$('preset').value;renderStress()});$('calc-btn').addEventListener('click',calculate);$('replay-btn').addEventListener('click',startReplay);$('cancel-btn').addEventListener('click',cancelReplay);$('upload-form').addEventListener('submit',validateUpload);
loadSnapshot();
</script>
</body></html>"""
